### PR TITLE
chore(test): fixing ts

### PR DESCRIPTION
**Pull request by lacymorrow**
Attempting to fix these issues: https://github.com/twilio-labs/match/runs/3899875183?check_suite_focus=true

### CODE REVIEW

**Review by BlakePetersen — APPROVED** [review]

**Comment by tomwanzek** [comment]
Can we please hold off on merging this one down. Thanks, will be speaking with @lacymorrow . Cheers 😄

**Comment by BlakePetersen** [comment]
Cool cool -- Can you post a summary of what is being discussed so the rest of the team has visibility ("Write It Down" ftw)? As a `match` and typescript noob, I'd love to have context as to why this isn't mergable 🙏

**Comment by tomwanzek** [comment]
I'll connect with @lacymorrow in a few minutes later today, as we started discussing it end of last week. Then I started digging a little more into Match and i.p. initial Accordion implementation. But after that, certainly, I will update with more detail.

**Comment by tomwanzek** [comment]
Have been working off a fork.

**Comment by BlakePetersen** [comment]
Ahhhhh gotcha -- sorry I thought there was an issue with the code itself. Good to know tho, thanks @tomwanzek =]

**Comment by tomwanzek** [comment]
@lacymorrow : Closing this PR. The TS issues were addressed in PR #167 . And I just included the addition of `yarn bootstrap` into the readme into PR #169 . 😄

**Pull request closed without merging**
