### PR TITLE
feat(accordion, badge): rework accordion and badge

### PR DESCRIPTION
**Pull request by tomwanzek**
This PR:

(1) Refactors and fixes the Accordion to:
* use Contexts for state management and inter-component communication,
* Breakout component hierarchy in a more idiomatic way by introducing the `AccordionItem` as the elements of the `Accordion` which wraps sibling `AccordionHeading` and `AccordionContent` components
* Improve keyboard support for tabbing and opening/closing Accordion Items with `Enter` and `space`
* makes certain fixes to the styling (e.g. border around entire Accordion Item)

(2) Makes certain fixes to the Badge including simply relying on `children` for content projection and related typing fixes
(3) Enhances the type-safety of certain validators to allow proper type-narrowing (including for tokens with string unions)

cc @lacymorrow @BlakePetersen 

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by BlakePetersen** [comment]
Might not be a thing here but we've had issues with `feat/` branches being interpreted as a folder in Admiral and borking things good n proper. Just a quick heads up for Admiral-bound properties but pretty sure it won't be an issue here 🤞

**Review by BlakePetersen — APPROVED** [review]
LGTM 🚀

**Comment by tomwanzek** [comment]
Good question about the branch name convention here. I went with what seems to be the convention for Match, based on the PR Labeler Action configuration 🤔 

Yet of course Admiral-related work would conceivably different.

**Review by lacymorrow — APPROVED** [review]
Great work here, I'm echoing blake's concerns since I think we've had problems deploying branches with slashes in the past, but it may have been in `twilio-docs`

**Pull request merged**
